from django.urls import path
import learn.views
urlpatterns = [
    path('',learn.views.index,name = 'index1'),
    path('index1',learn.views.index,name = 'index1'),
    path('course',learn.views.course_single,name = 'course'),
    path('news',learn.views.news,name = 'news'),
    path('about',learn.views.about,name = 'about'),
    path('registration',learn.views.registration,name='registration'),
    path('sec_reg',learn.views.sec_reg,name='sec_reg'),
    path('admin_reg',learn.views.admin_reg,name='admin_reg'),
    path('teacher_reg',learn.views.teacher_reg,name='teacher_reg'),
    path('student_reg',learn.views.student_reg,name='student_reg'),
    path('login',learn.views.login,name='login'),
    path('adminhome',learn.views.adminhome,name='adminhome'),
    path('add_blog', learn.views.add_blog, name='add_blog'),
    path('view_blog', learn.views.view_blog, name='view_blog'),
    path('contact', learn.views.contact, name='contact'),
    path('admin', learn.views.admin, name='admin'),
    path('update_prof', learn.views.update_prof, name='update_prof'),
    path('adm_prof', learn.views.adm_prof, name='adm_prof'),
    path('del_admin/<id>', learn.views.del_admin, name='del_admin'),
    path('edit_admin', learn.views.edit_admin, name='edit_admin'),
    path('bnb', learn.views.bnb, name='bnb'),
    path('blogs_admin', learn.views.blogs_admin, name='blogs_admin'),
    path('blog_approves', learn.views.blog_approves, name='blog_approves'),
    path('blog_rejects', learn.views.blog_rejects, name='blog_rejects'),
    path('blog_delete', learn.views.blog_delete, name='blog_delete'),
    path('upl_cer',learn.views.upload_cert, name= 'upl_cer'),
    path('del_cer',learn.views.delete_cert, name= 'del_cer'),
    path('abb',learn.views.about_content, name= 'abb'),
    path('block',learn.views.block, name= 'block'),
    path('feedbak',learn.views.feedbak, name= 'feedbak'),
    path('pass_req',learn.views.pass_req, name= 'pass_req'),
    path('sub_ad',learn.views.subject_ad, name= 'sub_ad'),
    path('message',learn.views.member_messages, name= 'message'),
    path('guest_message',learn.views.guest_messages, name= 'guest_message'),
    path('chapter_ad', learn.views.chapter_ad, name='chapter_ad'),
    path('cont_ad', learn.views.cont_ad, name='cont_ad'),
    path('logout', learn.views.logout, name='logout'),

]